apiVersion: v1
kind: Service
metadata:
  name: {{ include "supertokens.fullname" . }}
  labels:
    {{- include "supertokens.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3567
      protocol: TCP
      name: http
  selector:
    {{- include "supertokens.selectorLabels" . | nindent 4 }}
