# Default values for supertokens.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # -- docker repository without database postfix
  repository: supertokens/supertokens
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: "3.9"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Specifies the database settings
database:
  # -- database type ('postgresql' or 'mysql')
  type: postgresql
  # -- database name
  name: supertokens
  # -- database port
  port: 5432
  # -- database host address
  host: postgres
  # -- database username
  user: supertokens
  # TODO: Move this into a secret
  # -- database user password
  password: supersecretpassword

apiKeys:
  # -- enable the use of API Keys with supertokens-core
  enabled: false
  # -- list of API Keys to load and use with supertokens-core
  keys: []


serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- limit and requests for resources for supertokens-core container
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  # -- enable autoscaling of replicas
  enabled: false
  # -- minimal replica count when autoscaling
  minReplicas: 1
  # -- maximum replica count when autoscaling
  maxReplicas: 100
  # -- target CPU usage before autoscaling
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# nodeSelector: {}

# tolerations: []

# affinity: {}
  # podAntiAffinity:
  #   preferredDuringSchedulingIgnoredDuringExecution:
  #     - weight: 1
  #       podAffinityTerm:
  #         labelSelector:
  #           matchExpressions:
  #             - key: "app.kubernetes.io/name"
  #               operator: In
  #               values:
  #                 - supertokens
  #         topologyKey: kubernetes.io/hostname
